#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
proxy:
  address: 0.0.0.0:9192
  logNetwork: true
  logFrames: true
adminHttp:
  host: 0.0.0.0
  port: 9193
  endpoints:
    prometheus: {}
clusters:
  demo:
    bootstrap_servers: kafka:9092
filters:
- type: ApiVersions
- type: BrokerAddress
- type: ProduceRequestTransformation
  config:
    transformation: io.kroxylicious.proxy.internal.filter.ProduceRequestTransformationFilter$UpperCasing
